<?php

/**
 * @file janrain/jainrain.module
 *
 * This project integrates Drupal with the Janrain social networking publisher.
 *
 * @see http://janrain.com/
 */

// A registry of variable_get defaults.
include_once('includes/janrain.variables.inc');

/**
 * Implementation of hook_menu().
 */
function janrain_menu() {
  $items = array(
    'admin/settings/janrain' => array(
      'title' => 'Janrain',
      'description' => 'Administer the Janrain module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('janrain_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/janrain.admin.inc',
    ),
  );
  return $items;
}

/**
 * Implementation of hook_link().
 */
function janrain_link($type, $object, $teaser = FALSE) {
  static $id = 0;

  $links = array();

  if ($type == 'node' && in_array($object->type, janrain_variable_get('facebook_share_link_types'))) {
    if (!$teaser) {
      janrain_add_js();
      $title = janrain_variable_get('facebook_share_title_'. $object->type);
      if (!$title) {
        $title = janrain_variable_get('facebook_share_default_title');
      }
      $links['janrain_facebook_share_link_types'] = array(
        'title' => t($title),
        'href' => 'node/'. $object->nid,
        'attributes' => array('class' => 'janrain-link-social', 'id' => 'janrain-link-social-'. $id),
      );
      $settings = array(
        'janrain' => array(
          'janrain-link-social-'. $id => array(
            'title' => t($object->title),
            'subject' => strip_tags(node_teaser($object->body)),
            'url' => url('node/'. $object->nid, array('absolute' => TRUE)),
          ),
        ),
      );
      drupal_add_js($settings, 'setting');
    }
  }

  return $links;
}

function janrain_add_js() {
  static $added_js;

  if (!isset($added_js)) {
    drupal_add_js(drupal_get_path('module', 'janrain') .'/js/janrain.js');
    $rpx = base_path() . drupal_get_path('module', 'janrain') .'/rpx_xdcomm.html';
    $app_id = check_plain(janrain_variable_get('app_id'));
    $js = <<<JS
  var rpxJsHost = (("https:" == document.location.protocol) ? "https://" : "http://static.");
  document.write(unescape("%3Cscript src='" + rpxJsHost + "rpxnow.com/js/lib/rpx.js' type='text/javascript'%3E%3C/script%3E"));
JS;
    drupal_add_js($js, 'inline');
    $js = <<<JS
  RPXNOW.init({appId: '$app_id',
    xdReceiver: '$rpx'});
JS;
    drupal_add_js($js, 'inline');
    $added_js = TRUE;
  }
}
